name: Build and deploy latex sources to GitHub Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: dm.tex
        working_directory: Colloquiums/
        args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode 
        compiler: latexmk

    - name: Upload pdf document
      uses: actions/upload-artifact@v2
      with:
        name: dm
        path: Colloquiums/dm.pdf
  
  deploy:

    runs-on: ubuntu-latest

    # Деплой пока только на ветке add-compilation

    if: github.ref == 'refs/heads/add-compilation'

    needs: [build]

    steps:
      - name: Download Artifacts  # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: dm

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: add-compilation
          FOLDER: "dm"  # The deployment folder should match the name of the artifact. 
                          # Even though our project builds into the 'build' folder the  
                          # artifact name of 'site' must be placed here.
