# This is a basic workflow to help you get started with Actions

name: Check

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: sphericalpotatoinvacuum/matan-tex:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: files
        uses: futuratrepadeira/changed-files@v3.3.0
        with:
          repo-token: ${{ github.token }}
          pattern: '.*\.tex'

      - name: Compile changed files
        shell: bash
        run: |
          for changed_file in ${{ steps.files.outputs.files_created }} ${{ steps.files.outputs.files_updated }}; do
            dir=$(dirname "${changed_file}")
            base=$(basename "${changed_file}")
            pdflatex --output-directory="${dir}" "${changed_file}"
          done
